"""
exercise_db.py — In-memory exercise database for the Antigravity Engine.

Each exercise is tagged with goal affinity so the generator algorithm
can pick the right ones based on the user's target.
"""

from __future__ import annotations

# ─────────────────────── Exercise Catalogue ──────────────────────
# Each entry:
#   name, muscle_group, goals[], base_sets, base_reps, rest, video, intensity, cal_per_set, icon

EXERCISE_DATABASE: list[dict] = [
    # ──────────── Compound Lifts (Muscle Gain priority) ────────────
    {
        "name": "Barbell Back Squat",
        "muscle_group": "Legs",
        "goals": ["Muscle Gain", "Endurance"],
        "base_sets": 4,
        "base_reps": "8",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=ultWZbUMPL8",
        "intensity": "High",
        "cal_per_set": 12,
        "icon": "🦵",
    },
    {
        "name": "Barbell Bench Press",
        "muscle_group": "Chest",
        "goals": ["Muscle Gain"],
        "base_sets": 4,
        "base_reps": "8",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=rT7DgCr-3pg",
        "intensity": "High",
        "cal_per_set": 10,
        "icon": "🏋️",
    },
    {
        "name": "Conventional Deadlift",
        "muscle_group": "Back / Posterior Chain",
        "goals": ["Muscle Gain", "Endurance"],
        "base_sets": 4,
        "base_reps": "6",
        "rest": "120s",
        "video": "https://www.youtube.com/watch?v=op9kVnSso6Q",
        "intensity": "High",
        "cal_per_set": 14,
        "icon": "💪",
    },
    {
        "name": "Overhead Press",
        "muscle_group": "Shoulders",
        "goals": ["Muscle Gain"],
        "base_sets": 4,
        "base_reps": "8",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=2yjwXTZQDDI",
        "intensity": "High",
        "cal_per_set": 9,
        "icon": "🙆",
    },
    {
        "name": "Barbell Row",
        "muscle_group": "Back",
        "goals": ["Muscle Gain"],
        "base_sets": 4,
        "base_reps": "8",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
        "intensity": "High",
        "cal_per_set": 10,
        "icon": "🚣",
    },
    {
        "name": "Weighted Pull-Ups",
        "muscle_group": "Back / Biceps",
        "goals": ["Muscle Gain", "Endurance"],
        "base_sets": 3,
        "base_reps": "6",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
        "intensity": "High",
        "cal_per_set": 9,
        "icon": "🧗",
    },

    # ──────────── Isolation / Accessories (Muscle Gain) ────────────
    {
        "name": "Dumbbell Lateral Raise",
        "muscle_group": "Shoulders",
        "goals": ["Muscle Gain"],
        "base_sets": 3,
        "base_reps": "12",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=3VcKaXpzqRo",
        "intensity": "Medium",
        "cal_per_set": 5,
        "icon": "🦅",
    },
    {
        "name": "Dumbbell Bicep Curl",
        "muscle_group": "Biceps",
        "goals": ["Muscle Gain"],
        "base_sets": 3,
        "base_reps": "12",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
        "intensity": "Medium",
        "cal_per_set": 5,
        "icon": "💪",
    },
    {
        "name": "Tricep Rope Pushdown",
        "muscle_group": "Triceps",
        "goals": ["Muscle Gain"],
        "base_sets": 3,
        "base_reps": "12",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=vB5OHsJ3EME",
        "intensity": "Medium",
        "cal_per_set": 5,
        "icon": "🔽",
    },
    {
        "name": "Leg Press",
        "muscle_group": "Legs",
        "goals": ["Muscle Gain"],
        "base_sets": 3,
        "base_reps": "10",
        "rest": "90s",
        "video": "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
        "intensity": "Medium",
        "cal_per_set": 10,
        "icon": "🦵",
    },
    {
        "name": "Cable Fly",
        "muscle_group": "Chest",
        "goals": ["Muscle Gain"],
        "base_sets": 3,
        "base_reps": "12",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=Iwe6AmxVf7o",
        "intensity": "Medium",
        "cal_per_set": 6,
        "icon": "🦋",
    },

    # ──────────── HIIT / Cardio (Weight Loss priority) ─────────────
    {
        "name": "Burpees",
        "muscle_group": "Full Body",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 4,
        "base_reps": "15",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=dZgVxmf6jkA",
        "intensity": "High",
        "cal_per_set": 15,
        "icon": "🔥",
    },
    {
        "name": "Mountain Climbers",
        "muscle_group": "Core / Cardio",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 4,
        "base_reps": "30 sec",
        "rest": "20s",
        "video": "https://www.youtube.com/watch?v=nmwgirgXLYM",
        "intensity": "High",
        "cal_per_set": 12,
        "icon": "⛰️",
    },
    {
        "name": "Jump Squats",
        "muscle_group": "Legs / Cardio",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 4,
        "base_reps": "15",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=A-cFYWvaHr0",
        "intensity": "High",
        "cal_per_set": 13,
        "icon": "⬆️",
    },
    {
        "name": "Box Jumps",
        "muscle_group": "Legs / Plyometric",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 3,
        "base_reps": "12",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=52r_Ul5k03g",
        "intensity": "High",
        "cal_per_set": 11,
        "icon": "📦",
    },
    {
        "name": "Kettlebell Swings",
        "muscle_group": "Full Body",
        "goals": ["Weight Loss", "Endurance", "Muscle Gain"],
        "base_sets": 4,
        "base_reps": "15",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=YSxHifyI6s8",
        "intensity": "High",
        "cal_per_set": 14,
        "icon": "🔔",
    },
    {
        "name": "Battle Ropes",
        "muscle_group": "Arms / Cardio",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 4,
        "base_reps": "30 sec",
        "rest": "20s",
        "video": "https://www.youtube.com/watch?v=2J510CWxCtU",
        "intensity": "High",
        "cal_per_set": 13,
        "icon": "🪢",
    },
    {
        "name": "High Knees",
        "muscle_group": "Cardio",
        "goals": ["Weight Loss", "Endurance"],
        "base_sets": 3,
        "base_reps": "30 sec",
        "rest": "15s",
        "video": "https://www.youtube.com/watch?v=LJMrXG_vPQ8",
        "intensity": "Medium",
        "cal_per_set": 10,
        "icon": "🏃",
    },
    {
        "name": "Jumping Jacks",
        "muscle_group": "Cardio",
        "goals": ["Weight Loss"],
        "base_sets": 3,
        "base_reps": "30 sec",
        "rest": "15s",
        "video": "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
        "intensity": "Low",
        "cal_per_set": 8,
        "icon": "⭐",
    },

    # ──────────── Endurance / Conditioning ─────────────────────────
    {
        "name": "Rowing Machine Intervals",
        "muscle_group": "Full Body",
        "goals": ["Endurance", "Weight Loss"],
        "base_sets": 5,
        "base_reps": "500m",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=r7BXcopo-UM",
        "intensity": "High",
        "cal_per_set": 18,
        "icon": "🚣",
    },
    {
        "name": "Farmer's Walk",
        "muscle_group": "Full Body / Grip",
        "goals": ["Endurance", "Muscle Gain"],
        "base_sets": 4,
        "base_reps": "40m",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=Fkzk_RqlYig",
        "intensity": "Medium",
        "cal_per_set": 10,
        "icon": "🧑‍🌾",
    },
    {
        "name": "Sled Push",
        "muscle_group": "Legs / Cardio",
        "goals": ["Endurance", "Weight Loss"],
        "base_sets": 4,
        "base_reps": "20m",
        "rest": "60s",
        "video": "https://www.youtube.com/watch?v=Qw8q55JR5VY",
        "intensity": "High",
        "cal_per_set": 16,
        "icon": "🛷",
    },
    {
        "name": "Plank Hold",
        "muscle_group": "Core",
        "goals": ["Endurance", "Weight Loss"],
        "base_sets": 3,
        "base_reps": "45 sec",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=ASdvN_XEl_c",
        "intensity": "Medium",
        "cal_per_set": 5,
        "icon": "🧘",
    },
    {
        "name": "Wall Sit",
        "muscle_group": "Legs",
        "goals": ["Endurance"],
        "base_sets": 3,
        "base_reps": "45 sec",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=y-wV4Venusw",
        "intensity": "Medium",
        "cal_per_set": 6,
        "icon": "🧱",
    },
    {
        "name": "Jump Rope",
        "muscle_group": "Cardio / Calves",
        "goals": ["Endurance", "Weight Loss"],
        "base_sets": 4,
        "base_reps": "60 sec",
        "rest": "30s",
        "video": "https://www.youtube.com/watch?v=u3zgHI8QnqE",
        "intensity": "Medium",
        "cal_per_set": 12,
        "icon": "🪢",
    },
]
